In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [28]:
df = pd.read_csv(r'claims_and_patient.csv')

In [34]:
df = df.fillna(df.mean())

TypeError: can only concatenate str (not "int") to str

In [33]:
df

,claim id,claim date,claim line item,claim status,primary plan payment type,secondary plan payment type,tertiary plan payment type,primary plan name,secondary plan name,secondary plan name.1,...,procedure code,treatment code,treatment description,days supply,quantity,patient id,patient year of birth,patient gender source value,product id,product name
0,41439,12/27/18,1,,Medicare,,,MEDICARE MARYLAND (MD),,,...,71046,71046,"RADIOLOGIC EXAMINATION, CHEST; 2 VIEWS",,,122343,1973,M,,
1,98850,9/2/21,1,,Commercial,,,UNH-UNSPECIFIED,,,...,E0260,E0260,"HOSPITAL BED, SEMI-ELECTRIC (HEAD AND FOOT ADJ...",,,146620,1949,F,,
2,74412,3/15/18,3,,Medicare,,,MEDICARE B CALIFORNIA SOUTH (CA),,,...,11056,11056,PARING OR CUTTING OF BENIGN HYPERKERATOTIC LES...,,,150208,0,F,,
3,28608,4/13/19,1,,Medicare Part D,,,UH MED MENERAL,,,...,99213,99213,OFFICE OR OTHER OUTPATIENT VISIT FOR THE EVALU...,,,172631,1941,F,,
4,28608,4/13/19,4,,Medicare Part D,,,UH MED MENERAL,,,...,J0696,J0696,"INJECTION, CEFTRIAXONE SODIUM, PER 250 MG",,,172631,1941,F,409733801,CEFTRIAXONE SODIUM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,32152,12/8/18,1,,Commercial,,,BCS OF CA HMO (CA),,,...,71045,71045,"RADIOLOGIC EXAMINATION, CHEST; SINGLE VIEW",,,196185,1951,M,,
2196,64341,12/11/18,42,,Commercial,,,BCS OF CA HMO (CA),,,...,97167,97167,"OCCUPATIONAL THERAPY EVALUATION, HIGH COMPLEXI...",,,196185,1951,M,,
2197,64341,12/15/18,24,,Commercial,,,BCS OF CA HMO (CA),,,...,97110,97110,"THERAPEUTIC PROCEDURE, 1 OR MORE AREAS, EACH 1...",,,196185,1951,M,,
2198,64341,12/14/18,14,,Commercial,,,BCS OF CA HMO (CA),,,...,85025,85025,"BLOOD COUNT; COMPLETE (CBC), AUTOMATED (HGB, H...",,,196185,1951,M,,
2199,64341,12/19/18,34,,Commercial,,,BCS OF CA HMO (CA),,,...,97530,97530,"THERAPEUTIC ACTIVITIES, DIRECT (ONE-ON-ONE) PA...",,,196185,1951,M,,

In [29]:
df.head()

,claim id,claim date,claim line item,claim status,primary plan payment type,secondary plan payment type,tertiary plan payment type,primary plan name,secondary plan name,secondary plan name.1,...,procedure code,treatment code,treatment description,days supply,quantity,patient id,patient year of birth,patient gender source value,product id,product name
0,41439,12/27/18,1,,Medicare,,,MEDICARE MARYLAND (MD),,,...,71046,71046,"RADIOLOGIC EXAMINATION, CHEST; 2 VIEWS",,,122343,1973,M,,
1,98850,9/2/21,1,,Commercial,,,UNH-UNSPECIFIED,,,...,E0260,E0260,"HOSPITAL BED, SEMI-ELECTRIC (HEAD AND FOOT ADJ...",,,146620,1949,F,,
2,74412,3/15/18,3,,Medicare,,,MEDICARE B CALIFORNIA SOUTH (CA),,,...,11056,11056,PARING OR CUTTING OF BENIGN HYPERKERATOTIC LES...,,,150208,0,F,,
3,28608,4/13/19,1,,Medicare Part D,,,UH MED MENERAL,,,...,99213,99213,OFFICE OR OTHER OUTPATIENT VISIT FOR THE EVALU...,,,172631,1941,F,,
4,28608,4/13/19,4,,Medicare Part D,,,UH MED MENERAL,,,...,J0696,J0696,"INJECTION, CEFTRIAXONE SODIUM, PER 250 MG",,,172631,1941,F,409733801,CEFTRIAXONE SODIUM

In [30]:
df.describe()

           claim id  claim line item     patient id  patient year of birth
count   2200.000000      2200.000000    2200.000000            2200.000000
mean   56335.252727         7.629091  144513.083182            1686.057727
std    26786.013965        11.269434   28041.852752             672.828406
min    10194.000000         0.000000  100525.000000               0.000000
25%    33922.000000         1.000000  123424.000000            1944.000000
50%    57461.000000         3.000000  137748.000000            1949.000000
75%    82179.000000         8.000000  164700.000000            1957.000000
max    99930.000000        65.000000  199968.000000            2022.000000

In [22]:
df.dtypes

claim id                         int64
claim date                      object
claim line item                  int64
claim status                    object
primary plan payment type       object
secondary plan payment type     object
tertiary plan payment type      object
primary plan name               object
secondary plan name             object
secondary plan name.1           object
tertiary plan name              object
primary plan type               object
secondary plan type             object
tertiary plan type              object
reject code                     object
reject reason                   object
source claim type               object
referring provider doctor id    object
rendering provider doctor id    object
diagnosis code 1                object
diagnosis code 2                object
diagnosis code 3                object
diagnosis code 4                object
diagnosis code 5                object
diagnosis code 6                object
diagnosis code 7                object
diagnosis code 8                object
patient oop                     object
buy down                        object
paid by payer                   object
service bill amount             object
service allowed amount          object
out of pocket ask               object
primary payer pay amount        object
secondary payer pay amount      object
tertiary payer pay amount       object
product strength                object
procedure description           object
procedure code                  object
treatment code                  object
treatment description           object
days supply                     object
quantity                        object
patient id                       int64
patient year of birth            int64
patient gender source value     object
product id                      object
product name                    object
dtype: object

In [35]:
df["Patient age"] = 2024 - df["patient year of birth"]

In [36]:
df.dtypes

claim id                         int64
claim date                      object
claim line item                  int64
claim status                    object
primary plan payment type       object
secondary plan payment type     object
tertiary plan payment type      object
primary plan name               object
secondary plan name             object
secondary plan name.1           object
tertiary plan name              object
primary plan type               object
secondary plan type             object
tertiary plan type              object
reject code                     object
reject reason                   object
source claim type               object
referring provider doctor id    object
rendering provider doctor id    object
diagnosis code 1                object
diagnosis code 2                object
diagnosis code 3                object
diagnosis code 4                object
diagnosis code 5                object
diagnosis code 6                object
diagnosis code 7                object
diagnosis code 8                object
patient oop                     object
buy down                        object
paid by payer                   object
service bill amount             object
service allowed amount          object
out of pocket ask               object
primary payer pay amount        object
secondary payer pay amount      object
tertiary payer pay amount       object
product strength                object
procedure description           object
procedure code                  object
treatment code                  object
treatment description           object
days supply                     object
quantity                        object
patient id                       int64
patient year of birth            int64
patient gender source value     object
product id                      object
product name                    object
Patient age                      int64
dtype: object

In [38]:
df

,claim id,claim date,claim line item,claim status,primary plan payment type,secondary plan payment type,tertiary plan payment type,primary plan name,secondary plan name,secondary plan name.1,...,treatment code,treatment description,days supply,quantity,patient id,patient year of birth,patient gender source value,product id,product name,Patient age
0,41439,12/27/18,1,,Medicare,,,MEDICARE MARYLAND (MD),,,...,71046,"RADIOLOGIC EXAMINATION, CHEST; 2 VIEWS",,,122343,1973,M,,,51
1,98850,9/2/21,1,,Commercial,,,UNH-UNSPECIFIED,,,...,E0260,"HOSPITAL BED, SEMI-ELECTRIC (HEAD AND FOOT ADJ...",,,146620,1949,F,,,75
2,74412,3/15/18,3,,Medicare,,,MEDICARE B CALIFORNIA SOUTH (CA),,,...,11056,PARING OR CUTTING OF BENIGN HYPERKERATOTIC LES...,,,150208,0,F,,,2024
3,28608,4/13/19,1,,Medicare Part D,,,UH MED MENERAL,,,...,99213,OFFICE OR OTHER OUTPATIENT VISIT FOR THE EVALU...,,,172631,1941,F,,,83
4,28608,4/13/19,4,,Medicare Part D,,,UH MED MENERAL,,,...,J0696,"INJECTION, CEFTRIAXONE SODIUM, PER 250 MG",,,172631,1941,F,409733801,CEFTRIAXONE SODIUM,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,32152,12/8/18,1,,Commercial,,,BCS OF CA HMO (CA),,,...,71045,"RADIOLOGIC EXAMINATION, CHEST; SINGLE VIEW",,,196185,1951,M,,,73
2196,64341,12/11/18,42,,Commercial,,,BCS OF CA HMO (CA),,,...,97167,"OCCUPATIONAL THERAPY EVALUATION, HIGH COMPLEXI...",,,196185,1951,M,,,73
2197,64341,12/15/18,24,,Commercial,,,BCS OF CA HMO (CA),,,...,97110,"THERAPEUTIC PROCEDURE, 1 OR MORE AREAS, EACH 1...",,,196185,1951,M,,,73
2198,64341,12/14/18,14,,Commercial,,,BCS OF CA HMO (CA),,,...,85025,"BLOOD COUNT; COMPLETE (CBC), AUTOMATED (HGB, H...",,,196185,1951,M,,,73
2199,64341,12/19/18,34,,Commercial,,,BCS OF CA HMO (CA),,,...,97530,"THERAPEUTIC ACTIVITIES, DIRECT (ONE-ON-ONE) PA...",,,196185,1951,M,,,73

In [39]:
avg_age_by_drug = df.groupby('product name')['Patient age'].mean()

In [40]:
print(avg_age_by_drug)

product name
ACETAMINOPHEN                  64.000000
AVASTIN                      2024.000000
BETAMETHASONE SODIUM PHOS    2024.000000
CEFAZOLIN                      64.000000
CEFTRIAXONE SODIUM             84.000000
CIPROFLOXACIN I.V.-IN D5W      67.500000
CYANOCOBALAMIN                563.250000
DEPO-MEDROL                    47.000000
DEXAMETHASONE SODIUM PHOS      64.000000
DIPHENHYDRAMINE HCL            64.000000
DOTAREM                        67.000000
EXPAREL                        64.000000
FENTANYL CITRATE               66.666667
FERAHEME                       76.000000
FERRLECIT                      80.000000
FLUCELVAX QUADRIVALENT 20      63.000000
FLULAVAL QUADRIVALENT 202      64.000000
FLUZONE HIGH-DOSE PF 2023      80.000000
HECTOROL                       80.000000
HYDROMORPHONE HCL              68.000000
ISOVUE-300                     72.000000
KETOROLAC TROMETHAMINE         68.000000
LACTATED RINGERS               64.000000
LUCENTIS                       67.000000
MAGNESIUM SULFATE              71.000000
MIDAZOLAM HYDROCHLORIDE        64.000000
OMNIPAQUE                      60.000000
ONDANSETRON HYDROCHLORIDE      68.000000
ORTHOVISC                    2024.000000
PARSABIV                       80.000000
PENTACEL                        2.000000
PNEUMOVAX 23/5 DOSE            85.000000
PREVNAR 13                      2.000000
PROLIA                         72.000000
PROPOFOL                       64.000000
RITUXAN                        70.000000
ROTATEQ                         2.000000
SANDOSTATIN LAR DEPOT          13.000000
SODIUM CHLORIDE                75.000000
SOLU-MEDROL                    70.000000
TRIAMCINOLONE ACETONIDE        79.000000
VITRASE                        84.000000
                              354.140426
Name: Patient age, dtype: float64

In [47]:
unique_patients = df.groupby(["product name", "primary plan payment type"])["Patient age"].nunique().reset_index()

print(unique_patients)

                 product name primary plan payment type  Patient age
0               ACETAMINOPHEN              Mgd Medicaid            1
1                     AVASTIN           Medicare Part D            1
2   BETAMETHASONE SODIUM PHOS           Medicare Part D            1
3                   CEFAZOLIN              Mgd Medicaid            1
4          CEFTRIAXONE SODIUM                Commercial            1
5          CEFTRIAXONE SODIUM           Medicare Part D            1
6   CIPROFLOXACIN I.V.-IN D5W                Commercial            1
7   CIPROFLOXACIN I.V.-IN D5W           Medicare Part D            1
8              CYANOCOBALAMIN                  Medicare            2
9              CYANOCOBALAMIN              Mgd Medicaid            1
10                DEPO-MEDROL              Mgd Medicaid            1
11  DEXAMETHASONE SODIUM PHOS              Mgd Medicaid            1
12        DIPHENHYDRAMINE HCL              Mgd Medicaid            1
13                    DOTAREM                Commercial            1
14                    EXPAREL              Mgd Medicaid            1
15           FENTANYL CITRATE                  Medicare            1
16           FENTANYL CITRATE              Mgd Medicaid            1
17                   FERAHEME                  Medicare            1
18                  FERRLECIT                  Medicare            1
19  FLUCELVAX QUADRIVALENT 20                  Medicare            1
20  FLULAVAL QUADRIVALENT 202              Mgd Medicaid            1
21  FLUZONE HIGH-DOSE PF 2023           Medicare Part D            1
22                   HECTOROL                  Medicare            1
23          HYDROMORPHONE HCL                  Medicare            1
24          HYDROMORPHONE HCL              Mgd Medicaid            1
25                 ISOVUE-300                  Medicare            1
26     KETOROLAC TROMETHAMINE                  Medicare            1
27     KETOROLAC TROMETHAMINE              Mgd Medicaid            1
28           LACTATED RINGERS              Mgd Medicaid            1
29                   LUCENTIS                Commercial            1
30          MAGNESIUM SULFATE                Commercial            1
31          MAGNESIUM SULFATE                  Medicare            1
32    MIDAZOLAM HYDROCHLORIDE              Mgd Medicaid            1
33                  OMNIPAQUE           Medicare Part D            1
34  ONDANSETRON HYDROCHLORIDE                  Medicare            1
35  ONDANSETRON HYDROCHLORIDE              Mgd Medicaid            1
36                  ORTHOVISC                  Medicare            1
37                   PARSABIV                  Medicare            1
38                   PENTACEL              FFS Medicaid            1
39        PNEUMOVAX 23/5 DOSE                  Medicare            1
40                 PREVNAR 13              FFS Medicaid            1
41                     PROLIA                  Medicare            1
42                   PROPOFOL              Mgd Medicaid            1
43                    RITUXAN                  Medicare            1
44                    ROTATEQ              FFS Medicaid            1
45      SANDOSTATIN LAR DEPOT                  Medicare            1
46            SODIUM CHLORIDE                Commercial            1
47                SOLU-MEDROL                  Medicare            1
48    TRIAMCINOLONE ACETONIDE                Commercial            1
49                    VITRASE                  Medicare            1
50                                           Commercial           46
51                                         FFS Medicaid            6
52                                             Medicare           28
53                                      Medicare Part D           16
54                                         Mgd Medicaid           18
55                                      Unknown Medical            3